exclude: ^{{ cookiecutter.repo_name }}/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.0
    hooks:
      - id: add-trailing-comma

  # python code formatting
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [--line-length, "120"]
  # black formatting to code-strings within docstrings.
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.8.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [ black==20.8b1 ]

  # python import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.0
    hooks:
      - id: isort

  # json formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        types: [json]
